[package]
name = "gossip"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gossip"

[dependencies]
solana-gossip = { version = "=4.0.0", features = ["agave-unstable-api"] }
solana-sdk = { version = "=4.0.0" }
solana-net-utils = { version = "=4.0.0", features = ["agave-unstable-api"] }
tokio = { version = "1", features = ["full"] }
log = "0.4"
env_logger = "0.11"
clap = { version = "4", features = ["derive"] }
anyhow = "1"
